### ISSUE TITLE
File not found error, causes restarts frequently

### ISSUE THREAD

**Issue by arif-mansoori** [faisalthaheem/open-lpr#19]
Hi,

I have followed the instructions as given, but upon checking the status of the containers, it looks like some keep crashing and restart. One such log output is as below. Am I missing something. I have used tensorflow with AVX.

~/open-lpr$ docker logs --tail 50 --follow --timestamps open-lpr_platedetector_1
2021-11-29T05:35:41.396211499Z             'publishTo': {'exchange': 'platedetector',
2021-11-29T05:35:41.396227734Z                           'exchangeType': 'fanout',
2021-11-29T05:35:41.396243907Z                           'routingKey': 'platedetection'},
2021-11-29T05:35:41.396259992Z             'uri': 'amqp://guest:guest@broker:5672/%2F?connection_attempts=3&heartbeat=3600'},
2021-11-29T05:35:41.396276753Z  'detection': {'grayScale': False, 'loadHeight': 288, 'loadWidth': 384},
2021-11-29T05:35:41.396293575Z  'mongo': {'uri': 'mongodb://lpr:lpr@mongodb:27017'},
2021-11-29T05:35:41.396310473Z  'storage': {'path': '/filestorage'}}
2021-11-29T05:35:41.397132477Z Traceback (most recent call last):
2021-11-29T05:35:41.397201155Z   File "/openlpr/platedetector/platedetector.py", line 248, in <module>
2021-11-29T05:35:41.397219578Z     detector = PlateDetector(args)
2021-11-29T05:35:41.397235575Z   File "/openlpr/platedetector/platedetector.py", line 75, in __init__
2021-11-29T05:35:41.397251923Z     self.platedetector.init(
2021-11-29T05:35:41.397269621Z   File "/openlpr/shared/obj_detector.py", line 55, in init
2021-11-29T05:35:41.397285931Z     graph_def.ParseFromString(f.read())
2021-11-29T05:35:41.397303166Z   File "/usr/local/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 116, in read
2021-11-29T05:35:41.397319589Z     self._preread_check()
2021-11-29T05:35:41.397335750Z   File "/usr/local/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
2021-11-29T05:35:41.397352210Z     self._read_buf = _pywrap_file_io.BufferedInputStream(
2021-11-29T05:35:41.397368395Z tensorflow.python.framework.errors_impl.NotFoundError: /models/frozen_inference_graph.pb; No such file or directory
2021-11-29T05:35:56.434516362Z 2021-11-29 05:35:56.434078: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2
2021-11-29T05:35:56.434610575Z To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-29T05:35:56.472260404Z 2021-11-29 05:35:56.471863: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 1600000000 Hz
2021-11-29T05:35:56.473919137Z 2021-11-29 05:35:56.473409: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d5290bc460 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-11-29T05:35:56.473996539Z 2021-11-29 05:35:56.473524: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-11-29T05:35:56.487961414Z WARNING:tensorflow:From /openlpr/shared/obj_detector.py:53: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
2021-11-29T05:35:56.488047690Z Instructions for updating:
2021-11-29T05:35:56.488064938Z Use tf.gfile.GFile.
2021-11-29T05:35:56.489285728Z {'broker': {'consumeFrom': {'exchange': 'ftp',
2021-11-29T05:35:56.489358944Z                             'exchangeType': 'fanout',
2021-11-29T05:35:56.489376391Z                             'queueName': 'detection_enqueue',
2021-11-29T05:35:56.489392702Z                             'routingKey': 'new.request'},
2021-11-29T05:35:56.489409212Z             'publishTo': {'exchange': 'platedetector',
2021-11-29T05:35:56.489425323Z                           'exchangeType': 'fanout',
2021-11-29T05:35:56.489441595Z                           'routingKey': 'platedetection'},
2021-11-29T05:35:56.489457781Z             'uri': 'amqp://guest:guest@broker:5672/%2F?connection_attempts=3&heartbeat=3600'},
2021-11-29T05:35:56.489474766Z  'detection': {'grayScale': False, 'loadHeight': 288, 'loadWidth': 384},
2021-11-29T05:35:56.489491164Z  'mongo': {'uri': 'mongodb://lpr:lpr@mongodb:27017'},
2021-11-29T05:35:56.489507449Z  'storage': {'path': '/filestorage'}}
2021-11-29T05:35:56.493490566Z Traceback (most recent call last):
2021-11-29T05:35:56.493567594Z   File "/openlpr/platedetector/platedetector.py", line 248, in <module>
2021-11-29T05:35:56.493585966Z     detector = PlateDetector(args)
2021-11-29T05:35:56.493602852Z   File "/openlpr/platedetector/platedetector.py", line 75, in __init__
2021-11-29T05:35:56.493619612Z     self.platedetector.init(
2021-11-29T05:35:56.493636935Z   File "/openlpr/shared/obj_detector.py", line 55, in init
2021-11-29T05:35:56.493654095Z     graph_def.ParseFromString(f.read())
2021-11-29T05:35:56.493670568Z   File "/usr/local/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 116, in read
2021-11-29T05:35:56.493688091Z     self._preread_check()
2021-11-29T05:35:56.493705038Z   File "/usr/local/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
2021-11-29T05:35:56.493722049Z     self._read_buf = _pywrap_file_io.BufferedInputStream(
2021-11-29T05:35:56.493738434Z tensorflow.python.framework.errors_impl.NotFoundError: /models/frozen_inference_graph.pb; No such file or directory

docker container ls
CONTAINER ID   IMAGE                         COMMAND                  CREATED             STATUS                                  PORTS                                                                                                                                NAMES
073a7d75d8a4   openlpr/nodered:v10           "npm start -- --user…"   About an hour ago   Up 10 minutes                           1880/tcp, 0.0.0.0:1890->1890/tcp, :::1890->1890/tcp                                                                                  open-lpr_nodered_1
04ef40317219   openlpr/platedetector:2.0     "python3 /openlpr/pl…"   About an hour ago   Restarting (1) Less than a second ago                                                                                                                                        open-lpr_platedetector_1
86459a7c06bf   openlpr/plateclassifier:2.0   "python3 /openlpr/pl…"   About an hour ago   Up 1 second                                                                                                                                                                  open-lpr_plateclassifier_1
38b3d35e9e6d   openlpr/ftp:2.0               "python3 /openlpr/ft…"   About an hour ago   Up 10 minutes                           0.0.0.0:2121->2121/tcp, :::2121->2121/tcp                                                                                            open-lpr_ftp_1
e3acb5281515   openlpr/ocr:2.0               "python3 /openlpr/oc…"   About an hour ago   Restarting (1) Less than a second ago                                                                                                                                        open-lpr_ocr_1
18ec482b5e8e   rabbitmq:3.7.14-management    "docker-entrypoint.s…"   About an hour ago   Up 10 minutes                           4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 15671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp   open-lpr_broker_1
91d390e1ad64   mongo:4.1.11-bionic           "docker-entrypoint.s…"   About an hour ago   Up 10 minutes                           0.0.0.0:27017->27017/tcp, :::27017->27017/tcp

**Comment by faisalthaheem** [comment]
Hi there
Thank you for taking time out to report this issue.
The codebase has been overhauled, could you please try again and if still any issues please post here.
Thanks
